# Generated by Django 4.0.2 on 2022-03-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_remove_image_id_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
