# Generated by Django 4.0.2 on 2022-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('repository', models.CharField(max_length=255)),
                ('hook_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
