# Generated by Django 4.0.2 on 2022-03-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='hook_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ping_url', models.URLField()),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hook', to='github_integration.repository')),
            ],
        ),
    ]
