# Generated by Django 4.0.2 on 2022-03-08 20:51

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=pathlib.PurePosixPath('/home/spralja/dev/portfolio_website/portfolio_website/image_server/storage'))),
            ],
        ),
    ]
