# Generated by Django 4.0.2 on 2022-03-08 21:10

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=pathlib.PurePosixPath('image_server/storage')),
        ),
    ]
