# Generated by Django 4.0.2 on 2022-03-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0002_imagebinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebinary',
            name='binary',
            field=models.BinaryField(),
        ),
    ]
