# Generated by Django 4.0.3 on 2022-03-09 18:22

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0002_imagebinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=pathlib.PurePosixPath('image_server/temp')),
        ),
    ]
