# Generated by Django 4.0.2 on 2022-03-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0002_rename_name_image_uid_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='path',
        ),
    ]
