# Generated by Django 4.0.2 on 2022-03-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0003_rename_image_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='image',
        ),
    ]
