# Generated by Django 4.0.2 on 2022-03-06 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import portfolio_website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('_description', portfolio_website.models.MarkdownField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('repository', models.CharField(max_length=255)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('last_accessed', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 1, 0))),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about_me', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('picture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.picture')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.user'),
        ),
        migrations.CreateModel(
            name='StaticFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_files', to='main.remote')),
            ],
            options={
                'unique_together': {('remote', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='main.user')),
            ],
            options={
                'unique_together': {('user', 'title')},
            },
        ),
    ]
