# Generated by Django 4.0.2 on 2022-03-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
