# Generated by Django 4.0.2 on 2022-03-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_social_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gitlab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
    ]
