# Generated by Django 4.0.2 on 2022-02-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staticwebsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='remote',
        ),
        migrations.AddField(
            model_name='remote',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticfile',
            name='static_website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.staticwebsite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticwebsite',
            name='remote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.remote'),
        ),
    ]
