# Generated by Django 4.0.2 on 2022-02-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='parent',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='parent',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='parent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='parent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hobby',
            old_name='parent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='parent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='parent',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='parent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='technicalskill',
            old_name='parent',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='hobby',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='technicalskill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parent',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='main.user'),
            preserve_default=False,
        ),
    ]
