# Generated by Django 4.0.2 on 2022-02-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_parent_course_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user_picture',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.picture', unique=True),
        ),
    ]
