# Generated by Django 4.0.2 on 2022-02-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_staticfile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticwebsite',
            name='remote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_website', to='main.remote'),
        ),
    ]
