# Generated by Django 4.0.2 on 2022-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cv_user_picture_remove_picture_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(null=True),
        ),
    ]
