# Generated by Django 4.0.2 on 2022-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_github_alter_user_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
