# Generated by Django 4.0.2 on 2022-02-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_picture_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.picture'),
        ),
    ]
