# Generated by Django 4.0.2 on 2022-02-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='_description',
        ),
    ]
