# Generated by Django 4.0.2 on 2022-02-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_description_project__description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remote',
            old_name='object',
            new_name='git_object',
        ),
        migrations.AddField(
            model_name='remote',
            name='hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
