# Generated by Django 4.0.2 on 2022-02-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_object_remote_git_object_remote_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remote',
            old_name='hash',
            new_name='sha',
        ),
    ]
