# Generated by Django 4.0.2 on 2022-02-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_remote_sha_remote_last_accessed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remote',
            old_name='git_object',
            new_name='branch',
        ),
    ]
