# Generated by Django 4.0.2 on 2022-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gitlab',
            field=models.URLField(null=True),
        ),
    ]
