# Generated by Django 4.0.2 on 2022-02-25 19:04

from django.db import migrations
import portfolio_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_gitlab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=portfolio_website.models.MarkdownField(blank=True),
        ),
    ]
