# Generated by Django 4.0.2 on 2022-02-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_remote_last_accessed_remote_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote',
            name='sha',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
