# Generated by Django 4.0.2 on 2022-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_remote_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote',
            name='sha',
            field=models.CharField(default='4f629bd7f1c20a1e23c0175dfff2ee23a249cb46', max_length=255),
        ),
    ]
