# Generated by Django 4.0.2 on 2022-02-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.URLField()),
            ],
        ),
    ]
