# Generated by Django 4.0.2 on 2022-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_staticwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticwebsite',
            name='tracked',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
