# Generated by Django 4.0.2 on 2022-02-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_staticwebsite_tracked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticwebsite',
            name='remote',
        ),
        migrations.AddField(
            model_name='staticwebsite',
            name='github_repository_name',
            field=models.CharField(default='portfolio_website', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticwebsite',
            name='github_user_name',
            field=models.CharField(default='spralja', max_length=255),
            preserve_default=False,
        ),
    ]
