# Generated by Django 4.0.2 on 2022-02-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_html_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
