# Generated by Django 4.0.2 on 2022-02-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_staticwebsite_remote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticwebsite',
            name='tracked',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
