# Generated by Django 4.0.2 on 2022-02-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_staticwebsite_tracked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticwebsite',
            name='github_repository_name',
        ),
        migrations.RemoveField(
            model_name='staticwebsite',
            name='github_user_name',
        ),
        migrations.AddField(
            model_name='staticwebsite',
            name='remote',
            field=models.URLField(default='https://github.com/spralja/path-finding-algorithms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticwebsite',
            name='tracked',
            field=models.CharField(max_length=255),
        ),
    ]
