# Generated by Django 4.0.2 on 2022-02-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_static'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='static',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='static',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='static',
            unique_together={('project', 'name')},
        ),
    ]
