# Generated by Django 4.0.2 on 2022-02-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_static_unique_together_static_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='static',
            unique_together=set(),
        ),
    ]
