# Generated by Django 4.0.2 on 2022-02-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticwebsite',
            name='name',
            field=models.CharField(default='path-finding-algorithms', max_length=255),
            preserve_default=False,
        ),
    ]
