# Generated by Django 4.0.2 on 2022-02-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_staticwebsite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticwebsite',
            name='tracked',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
