# Generated by Django 4.0.2 on 2022-02-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_staticwebsite_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staticwebsite', unique=True),
        ),
    ]
