# Generated by Django 4.0.2 on 2022-02-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_remote_last_accessed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staticfile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staticfile',
            name='remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_files', to='main.remote'),
        ),
        migrations.AlterUniqueTogether(
            name='staticfile',
            unique_together={('remote', 'name')},
        ),
        migrations.RemoveField(
            model_name='staticfile',
            name='static_website',
        ),
        migrations.DeleteModel(
            name='StaticWebsite',
        ),
    ]
