# Generated by Django 4.0.2 on 2022-02-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_staticfile_unique_together_staticfile_remote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfile',
            name='remote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_files', to='main.remote'),
        ),
    ]
