# Generated by Django 4.0.2 on 2022-02-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_education_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.cv'),
        ),
    ]
