# Generated by Django 3.2.7 on 2021-10-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_experience_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
    ]
