# Generated by Django 4.0.2 on 2022-02-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_education_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv.cv'),
        ),
    ]
