# Generated by Django 3.2.7 on 2021-10-01 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20211001_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
