# Generated by Django 4.0.2 on 2022-02-15 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_experience_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 13, 5, 17, 300584)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
