# Generated by Django 4.0.2 on 2022-02-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_experience_time_frame_experience_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='education',
        ),
        migrations.AddField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cv.education'),
        ),
    ]
