# Generated by Django 3.2.7 on 2021-10-01 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_experience_start_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
