# Generated by Django 4.0.2 on 2022-02-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_course_education_course_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cv.education'),
        ),
    ]
