# Generated by Django 4.0.2 on 2022-02-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_course_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='education',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv.education'),
        ),
    ]
