# Generated by Django 3.2.7 on 2021-10-01 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20211001_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
