# Generated by Django 3.2.7 on 2021-10-01 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_experience_start_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_year',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cv.date'),
        ),
    ]
