# Generated by Django 4.0.2 on 2022-02-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_project_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicture',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='hobby',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv.cv'),
        ),
        migrations.AddField(
            model_name='language',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.cv'),
        ),
        migrations.AddField(
            model_name='userpicture',
            name='alt',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
