# Generated by Django 3.2.7 on 2021-10-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_remove_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.date'),
        ),
    ]
