# Generated by Django 4.0.2 on 2022-02-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_remove_userpicture_alt_text_hobby_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv.cv'),
        ),
        migrations.AlterField(
            model_name='language',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.cv'),
        ),
    ]
