# Generated by Django 3.2.7 on 2021-10-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.date'),
        ),
    ]
