# Generated by Django 4.0.2 on 2022-02-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_alter_hobby_parent_alter_language_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='experience',
        ),
        migrations.AddField(
            model_name='description',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cv.experience'),
        ),
    ]
