# Generated by Django 4.0.2 on 2022-02-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_remove_description_experience_description_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cv.experience'),
        ),
    ]
