# Generated by Django 3.2.7 on 2021-10-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_auto_20211002_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.experience')),
            ],
        ),
    ]
