# Generated by Django 4.0.2 on 2022-02-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_alter_description_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='parent',
        ),
    ]
