# Generated by Django 3.2.7 on 2021-10-02 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_auto_20211002_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_end_date', to='cv.date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_start_date', to='cv.date'),
        ),
    ]
