# Generated by Django 3.2.7 on 2021-10-02 03:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_auto_20211002_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('gpa', models.FloatField(validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(12.0)])),
                ('end_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_end_date', to='cv.date')),
                ('start_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_start_date', to='cv.date')),
            ],
        ),
    ]
