# Generated by Django 4.0.2 on 2022-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_alter_technicalskill_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='alt',
            field=models.CharField(max_length=200),
        ),
    ]
