# Generated by Django 4.0.2 on 2022-02-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_alter_hobby_name_alter_technicalskill_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='cv.cv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ResumeParagraph',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='cv.resume'),
        ),
    ]
