# Generated by Django 4.0.2 on 2022-02-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_paragraph_resume_delete_resumeparagraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='cv.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='cv.cv'),
        ),
    ]
