# Generated by Django 4.0.2 on 2022-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_alter_paragraph_parent_alter_resume_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(default='https://github.com/spralja'),
            preserve_default=False,
        ),
    ]
