# Generated by Django 3.2.7 on 2021-10-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_auto_20211002_0656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date2',
            new_name='Lanuguage',
        ),
    ]
