# Generated by Django 4.0.2 on 2022-02-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0025_cv_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user_heading',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parent',
        ),
        migrations.AddField(
            model_name='cv',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='heading',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
