# Generated by Django 4.0.2 on 2022-02-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0026_remove_cv_user_heading_remove_resume_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.resume'),
        ),
    ]
