# Generated by Django 3.2.7 on 2021-10-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0026_rename_month_lanuguage_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanuguage',
            name='level',
            field=models.IntegerField(choices=[(1, 'elementary'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
