# Generated by Django 4.0.2 on 2022-02-15 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0027_alter_cv_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 14, 16, 12, 87740)),
            preserve_default=False,
        ),
    ]
