# Generated by Django 4.0.2 on 2022-02-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0028_alter_education_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_time',
            field=models.DateField(),
        ),
    ]
