# Generated by Django 4.0.2 on 2022-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_alter_education_end_time_alter_education_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
