# Generated by Django 4.0.2 on 2022-02-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0030_alter_experience_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='hobby',
            unique_together={('parent', 'name')},
        ),
    ]
