# Generated by Django 4.0.2 on 2022-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_alter_hobby_name_alter_hobby_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('parent', 'name')},
        ),
    ]
