# Generated by Django 3.2.7 on 2021-10-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_alter_lanuguage_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanuguage',
            name='level',
            field=models.IntegerField(choices=[(1, 'elementary'), (2, 'professional'), (3, 'fluent'), (4, 'bilingual'), (5, 'native'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November')]),
        ),
    ]
