# Generated by Django 4.0.2 on 2022-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0032_language_id_alter_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(choices=[(1, 'elementary'), (2, 'professional'), (3, 'fluent')]),
        ),
    ]
