# Generated by Django 4.0.2 on 2022-02-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0033_alter_language_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technicalskill',
            unique_together={('parent', 'name')},
        ),
    ]
