# Generated by Django 4.0.2 on 2022-02-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0034_alter_technicalskill_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
