# Generated by Django 3.2.7 on 2021-10-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0035_alter_lanuguage_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lanuguage',
            new_name='Language',
        ),
    ]
