# Generated by Django 3.2.7 on 2021-10-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0036_rename_lanuguage_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='year',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='t', max_length=200),
            preserve_default=False,
        ),
    ]
