# Generated by Django 4.0.2 on 2022-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0036_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.AlterField(
            model_name='resume',
            name='heading',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
