# Generated by Django 4.0.2 on 2022-02-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0037_remove_resume_id_alter_resume_heading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Résumé'},
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
