# Generated by Django 3.2.7 on 2021-10-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0037_auto_20211002_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
