# Generated by Django 3.2.7 on 2021-10-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0039_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'Hobbies'},
        ),
    ]
