# Generated by Django 4.0.2 on 2022-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0039_alter_course_description_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
