# Generated by Django 3.2.7 on 2021-10-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0040_auto_20211002_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_date', to='cv.date')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_date', to='cv.date')),
            ],
        ),
    ]
