# Generated by Django 4.0.2 on 2022-02-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0041_user_cv_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='cv.user'),
        ),
    ]
