# Generated by Django 4.0.2 on 2022-02-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0042_alter_cv_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'Curriculum Vitae', 'verbose_name_plural': 'Curricula Vitae'},
        ),
    ]
