# Generated by Django 4.0.2 on 2022-02-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0043_alter_cv_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user_name',
        ),
    ]
