# Generated by Django 3.2.7 on 2021-10-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0044_auto_20211002_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='time_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.timeframe'),
        ),
    ]
