# Generated by Django 4.0.2 on 2022-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0045_alter_education_time_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_heading', models.TextField()),
            ],
        ),
    ]
