# Generated by Django 4.0.2 on 2022-02-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0045_remove_cv_github_remove_cv_linkedin_user_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cv.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cv',
            name='user_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.picture'),
        ),
        migrations.DeleteModel(
            name='UserPicture',
        ),
    ]
