# Generated by Django 4.0.2 on 2022-02-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0046_picture_alter_cv_user_picture_delete_userpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv.user'),
        ),
    ]
