# Generated by Django 4.0.2 on 2022-02-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0046_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
        ),
    ]
