# Generated by Django 4.0.2 on 2022-02-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0046_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='user_picture',
            field=models.URLField(null=True),
        ),
    ]
