# Generated by Django 4.0.2 on 2022-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0047_cv_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user_picture',
            field=models.URLField(),
        ),
    ]
