# Generated by Django 4.0.2 on 2022-02-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0047_experience_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
        ),
    ]
