# Generated by Django 4.0.2 on 2022-02-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0048_alter_experience_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='experiences',
            field=models.ManyToManyField(to='cv.Experience'),
        ),
        migrations.AlterField(
            model_name='education',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.cv'),
        ),
    ]
