# Generated by Django 4.0.2 on 2022-02-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0048_alter_cv_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
