# Generated by Django 4.0.2 on 2022-02-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0049_remove_cv_user_picture_experience_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
        ),
    ]
