# Generated by Django 4.0.2 on 2022-02-20 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0049_cv_experiences_alter_education_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.user'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='cv.user'),
        ),
        migrations.AlterField(
            model_name='language',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.user'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='cv.user'),
        ),
    ]
