# Generated by Django 4.0.2 on 2022-02-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0050_alter_education_parent_alter_hobby_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='educations',
            field=models.ManyToManyField(to='cv.Education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='hobbies',
            field=models.ManyToManyField(to='cv.Hobby'),
        ),
        migrations.AddField(
            model_name='cv',
            name='languages',
            field=models.ManyToManyField(to='cv.Language'),
        ),
        migrations.AddField(
            model_name='cv',
            name='technical_skills',
            field=models.ManyToManyField(to='cv.TechnicalSkill'),
        ),
    ]
