# Generated by Django 4.0.2 on 2022-02-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0051_alter_education_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_education', to='cv.cv'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_experience', to='cv.cv'),
        ),
    ]
