# Generated by Django 4.0.2 on 2022-02-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0051_cv_educations_cv_hobbies_cv_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cv.user'),
        ),
    ]
