# Generated by Django 4.0.2 on 2022-02-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0052_alter_picture_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='cv.user'),
        ),
    ]
