# Generated by Django 4.0.2 on 2022-02-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0054_alter_resume_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.user'),
        ),
    ]
