# Generated by Django 4.0.2 on 2022-02-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0055_alter_education_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='parent',
        ),
    ]
