# Generated by Django 4.0.2 on 2022-02-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0056_alter_project_unique_together_remove_project_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='parent',
        ),
    ]
