# Generated by Django 4.0.2 on 2022-02-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0057_remove_course_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='courses',
            field=models.ManyToManyField(to='cv.Course'),
        ),
        migrations.AddField(
            model_name='education',
            name='projects',
            field=models.ManyToManyField(to='cv.Project'),
        ),
    ]
