# Generated by Django 4.0.2 on 2022-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0058_education_courses_education_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='id',
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
