# Generated by Django 4.0.2 on 2022-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0059_remove_description_id_alter_description_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
