# Generated by Django 4.0.2 on 2022-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0060_alter_description_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='parent',
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.ManyToManyField(to='cv.Description'),
        ),
    ]
