# Generated by Django 4.0.2 on 2022-02-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0061_remove_description_parent_experience_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='descriptions',
        ),
    ]
