# Generated by Django 4.0.2 on 2022-02-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0062_rename_description_experience_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='description',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cv.experience'),
        ),
    ]
