# Generated by Django 4.0.2 on 2022-02-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0063_remove_experience_descriptions_description_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cv.experience'),
        ),
    ]
