# Generated by Django 4.0.2 on 2022-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0064_alter_description_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='courses',
            field=models.ManyToManyField(blank=True, to='cv.Course'),
        ),
        migrations.AlterField(
            model_name='education',
            name='projects',
            field=models.ManyToManyField(blank=True, to='cv.Project'),
        ),
    ]
