# Generated by Django 4.0.2 on 2022-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0065_alter_education_courses_alter_education_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='educations',
            field=models.ManyToManyField(blank=True, to='cv.Education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='cv.Experience'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='cv.Hobby'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='languages',
            field=models.ManyToManyField(blank=True, to='cv.Language'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='technical_skills',
            field=models.ManyToManyField(blank=True, to='cv.TechnicalSkill'),
        ),
    ]
