# Generated by Django 4.0.2 on 2022-02-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0067_remove_course_description_remove_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cv.education'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv.education'),
        ),
    ]
