# Generated by Django 4.0.2 on 2022-02-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0068_alter_course_parent_alter_project_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='parent',
            new_name='user',
        ),
    ]
